export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const TOKEN_USER_REQ = 'TOKEN_USER_REQ';
export const TOKEN_USER_SUCCESS = 'TOKEN_USER_SUCCESS';
export const TOKEN_USER_FAIL = 'TOKEN_USER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';
export const BIO_UPDATE_SUCCESS = 'BIO_UPDATE_SUCCESS';
export const BIO_UPDATE_FAIL = 'BIO_UPDATE_FAIL';

